name: Backend Continuous Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  
env:
  PYTHON_VERSION: '3.10'

jobs:
  Linting:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: backend

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Lint code
      run: pipenv run lint

  Test:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: backend

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}
    
    - name: Install Dependencies
      run: |
        pip install pipenv
        pipenv install

    - name: Run tests
      run: pipenv run test

  Deploy:
    runs-on: ubuntu-latest
    needs: [Linting, Test]
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      working-directory: backend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA} .
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}
    
    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --name cluster --region us-east-1

    - name: Deploy to EKS
      working-directory: backend/k8s
      run: |
        kustomize edit set image backend=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}
        kustomize build | kubectl apply -f -
    - name: Url        
      run: |
        cd backend/k8s
        kubectl get svc -A