name: Backend Continuous Integration

# Triggers 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.6
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6' 

      - name: Install pipenv
        run: pip install pipenv --user

      - name: Install flake8
        run: pip install flake8

      - name: Install dependencies
        run: pipenv install

      - name: Run the lint
        run: pipenv run lint

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.6
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6' 

      - name: Install pipenv
        run: pip install pipenv --user

      - name: Install dependencies
        run: pipenv install

      - name: Run tests
        run: pipenv run test

  build:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.6
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6' 

      - name: Install pipenv
        run: pip install pipenv --user

      - name: Install dependencies
        run: pipenv install

      - name: Build docker image
        run: docker build --tag mp-backend:latest .

      - name: Run docker container
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend
